In [3]:
import numpy as np

In [2]:
a = np.zeros([2,3])

In [4]:
a.shape[0]

2

In [5]:
a=np.array([[1,2], [3,4], [5,6], [7,8]])

In [6]:
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [12]:
b=a.flatten()

In [13]:
np.diag(b)

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0, 0, 0, 8]])

In [15]:
np.arange(-2,3)

array([-2, -1,  0,  1,  2])

In [17]:
M = 2
N = 1

p = np.arange(-M, M+1)
q = np.arange(-N, N+1)

P, Q = np.meshgrid(p, q)

In [18]:
P

array([[-2, -1,  0,  1,  2],
       [-2, -1,  0,  1,  2],
       [-2, -1,  0,  1,  2]])

In [19]:
Q

array([[-1, -1, -1, -1, -1],
       [ 0,  0,  0,  0,  0],
       [ 1,  1,  1,  1,  1]])

In [4]:
import rcwa

In [6]:
M = 0
N = 1
Px = 1
Py = 2
Kx, Ky = rcwa.create_k_space(Px, Py, 0, 0, M, N, alpha=np.pi/2)

[[0]
 [0]
 [0]]
[[-1]
 [ 0]
 [ 1]]


In [8]:
Ky

array([[-3.14159265,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  3.14159265]])